buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.12.1'
    }
}

apply plugin: 'com.android.library'

android {
    namespace 'com.facebook.crypto'

    compileSdk = 35

    defaultConfig {
        minSdk = 21
        targetSdk = 35

        ndk {
            abiFilters "arm64-v8a", "armeabi-v7a", "x86", "x86_64"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    externalNativeBuild {
        ndkBuild {
            path "native/jni/Android.mk"
        }
    }

    ndkVersion = "27.0.12077973"

    sourceSets {
        main {
            manifest.srcFile "src/main/AndroidManifest.xml"
            java.srcDirs = [
                    "first-party/fbjni/java",
                    "first-party/proguard/annotations",
                    "first-party/soloader",
                    "java"
            ]
            jniLibs.srcDir "libs"
        }
    }

    lint {
        abortOnError = false
    }
}

repositories {
    google()
    mavenCentral()
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.google.code.findbugs:jsr305:3.0.2"
}